graph LR
    classDef exposures fill:#e74c3c,stroke:#333,stroke-width:2px;
    classDef mitigations fill:#2ecc71,stroke:#333,stroke-width:2px;
    classDef transfers fill:#9b59b6,stroke:#333,stroke-width:2px;
    classDef acceptances fill:#f39c12,stroke:#333,stroke-width:2px;
    classDef reviews fill:#3498db,stroke:#333,stroke-width:2px;
    subgraph Web
        web_web_sg("WebServerSecurityGroup")
        web_web_group("WebServerASGGroup")
        web_elb("ElasticLoadBalancer")
        web_web_group --- web_web_sg
        web_elb -- http tcp/80 --> web_web_sg
    end

    subgraph Database
        db_db_ec2_sg("DBEC2SecurityGroup")
        db_db_sg("DBSecurityGroup")
        db_db("MySQLDatabase")
        db_db_ec2_sg --- db_db
        db_db_sg --- db_db_ec2_sg
        db_db_sg --- db_db
    end

    subgraph External
        external_user("User")
    end

    subgraph Management
        mgmt_admin("Administrator")
    end

    cwe_311_missing_encryption_of_sensitive_data_3LBTB38IPD>" Exposed to Missing Encryption of Sensitive<br/> Data with lack of TLS"]
    class cwe_311_missing_encryption_of_sensitive_data_3LBTB38IPD exposures
    cwe_311_missing_encryption_of_sensitive_data_3LBTB38IPD-.-web_elb
    cwe_306_missing_authentication_for_critical_function_D4H9BEI33A>" Mitigated against Missing Authentication<br/> for Critical Function with use of secure<br/> shell"]
    class cwe_306_missing_authentication_for_critical_function_D4H9BEI33A mitigations
    cwe_306_missing_authentication_for_critical_function_D4H9BEI33A-.-web_web_sg
    cwe_311_missing_encryption_of_sensitive_data_E2XEZ2O76Q>" Mitigated against Missing Encryption of Sensitive<br/> Data with use of secure shell"]
    class cwe_311_missing_encryption_of_sensitive_data_E2XEZ2O76Q mitigations
    cwe_311_missing_encryption_of_sensitive_data_E2XEZ2O76Q-.-web_web_sg
    cwe_807_reliance_on_untrusted_inputs_in_a_security_decision_QTWWIL5QFB>" Transfers Reliance on Untrusted Inputs in<br/> a Security Decision with lack of WAF"]
    class cwe_807_reliance_on_untrusted_inputs_in_a_security_decision_QTWWIL5QFB transfers
    cwe_807_reliance_on_untrusted_inputs_in_a_security_decision_QTWWIL5QFB-.-web_web_group
    cwe_311_missing_encryption_of_sensitive_data_VH07BGQNE1>" Transfers Missing Encryption of Sensitive<br/> Data with mysql client TLS selection"]
    class cwe_311_missing_encryption_of_sensitive_data_VH07BGQNE1 transfers
    cwe_311_missing_encryption_of_sensitive_data_VH07BGQNE1-.-web_web_group
    admin_credentials_0H5VDYOP0I>"Review admin credentials"]
    class admin_credentials_0H5VDYOP0I reviews
    admin_credentials_0H5VDYOP0I-.-db_db
    ssh_keypair_MRKS6WUQIQ>"Review ssh keypair"]
    class ssh_keypair_MRKS6WUQIQ reviews
    ssh_keypair_MRKS6WUQIQ-.-web_web_group

    external_user == http tcp/80 ==> web_elb
    mgmt_admin == ssh tcp/22 ==> web_web_sg
    web_web_sg == mysql tcp/3306 ==> db_db_ec2_sg

